"""
Revision ID: e938fbc52236
Revises: e7c5ed41fae0
Create Date: 2026-02-26 04:44:00.430858+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e938fbc52236"
down_revision: Union[str, None] = "e7c5ed41fae0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("roblox_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "roblox_username",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=True,
        ),
        sa.Column("verified_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "discord_id > 0", name="check_verification_discord_id_valid"
        ),
        sa.CheckConstraint("roblox_id > 0", name="check_verification_roblox_id_valid"),
        sa.PrimaryKeyConstraint("discord_id"),
    )
    with op.batch_alter_table("verification", schema=None) as batch_op:
        batch_op.create_index("idx_verification_roblox", ["roblox_id"], unique=False)

    with op.batch_alter_table("levels", schema=None) as batch_op:
        batch_op.drop_table_comment(existing_comment="f")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("levels", schema=None) as batch_op:
        batch_op.create_table_comment("f", existing_comment=None)

    with op.batch_alter_table("verification", schema=None) as batch_op:
        batch_op.drop_index("idx_verification_roblox")

    op.drop_table("verification")
    # ### end Alembic commands ###
